apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: {{ .Values.namespace }}
  labels:
    app: order-api
    {{- include "orderflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: order-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "{{ .Values.api.containerPort }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: order-api
          image: "{{ include "orderflow.image" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          env:
            - name: GCP_PROJECT_ID
              value: {{ .Values.pubsub.projectId | quote }}
            - name: ORDERS_TOPIC
              value: {{ .Values.pubsub.ordersTopic | quote }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.api.containerPort }}
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.api.containerPort }}
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.api.containerPort }}
            periodSeconds: 10
            failureThreshold: 3
