apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-api-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: order-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-worker-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: order-worker
