{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: orderflow-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
{{- end }}
{{- if .Values.limitRange.enabled }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: orderflow-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultCpu }}
        memory: {{ .Values.limitRange.defaultMemory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu }}
        memory: {{ .Values.limitRange.defaultRequestMemory }}
{{- end }}
