apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: {{ .Values.namespace }}
  labels:
    app: order-api
    {{- include "orderflow.labels" . | nindent 4 }}
spec:
  selector:
    app: order-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
  type: ClusterIP
